name: Splunk TA Builder

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: tar package files
      run: |
        COPYFILE_DISABLE=1 tar --format ustar -cvzf ./ta-${{ github.ref_name }}-csnf.tar.gz ta-csnf/
        tar -tvf ./ta-${{ github.ref_name }}-csnf.tar.gz
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ta-${{ github.ref_name }}-csnf.tar.gz
# curl -X POST \
#    -H "Authorization: bearer <TOKEN>" \
#    -H "Cache-Control: no-cache" \
#    -F "app_package=@\"/<./ta-csnf.tar.gz>\"" \
#    -F "included_tags=cloud" \
#    --url "https://appinspect.splunk.com/v1/app/validate"
