name: Splunk TA Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: tar package files
      run: |
        COPYFILE_DISABLE=1 tar --format ustar -cvzf ta-csnf.tar.gz ta-csnf/
        tar -tvf ./ta-csnf.tar.gz
